# Generated by Django 5.1.3 on 2024-12-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_user_ciudad_user_codigo_postal_user_direccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
