# Generated by Django 5.1.3 on 2024-12-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0004_alter_cartitem_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Artículo del carrito', 'verbose_name_plural': 'Artículos del carrito'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Dirección de envío', 'verbose_name_plural': 'Direcciones de envío'},
        ),
    ]
